### ISSUE TITLE
Gassetic with static files

### ISSUE THREAD

**Issue by tzi** [romanschejbal/gassetic#29]
Hi!

Thanks for sharing this awesome tool!

I used to use gassetic with dynamique html pages, so I can have code like this one:

``` html
    {% if platform == 'dev' %}
        <!-- dev:styles.css --><!-- endbuild -->
    {% else %}
        <!-- prod:styles.css --><!-- endbuild -->
    {% endif %}
```

It works perfectly!
What if I should use gassetic with static file, how can I do that?
Is there a way to have a platform agnostic tag?

``` html
      <!-- *:styles.css --><!-- endbuild -->
```

Cheers,
Thomas.

**Comment by jdeniau** [comment]
Great functionality !
It should be documented though.
