### ISSUE TITLE
Add config option for brackets pattern

### ISSUE THREAD

**Issue by discane** [romanschejbal/gassetic#57]
For those who use the Twig, construction `<-- {env}:{file} -->` can be replaced by `{# {env}:{file} #}` for cleaning output html, and default for other users.
Maybe add to gassetic.yaml parameter with default value `['<--', '-->']`?
`replace_brackets: ['{#', '#}']`

**Comment by romanschejbal** [comment]
Closing this since we are going in a slightly different direction. See #62
