### ISSUE TITLE
Issue with dependency fesevent

### ISSUE THREAD

**Issue by Getuser31** [romanschejbal/gassetic#67]
Hello, 
I have an issue with latest version of gassetic. It required a depency on fesevent, which is not compatible with ubuntu 16.04 apprently:
https://github.com/npm/npm/issues/14042#issuecomment-260971232

The solution in this comment is working, but as it's an optional dependency why just no remove it? 
Thx for attention and thx for your work. Have a nice day

**Comment by romanschejbal** [comment]
I can't remove it since it's used inside of the other modules, but I've added it to optionalDependencies to see if it helps. Can you please try now with the version 1.0.7? Thanks!

**Comment by Getuser31** [comment]
Work great. thx a lot. Have a nice day
