### ISSUE TITLE
gulp-replace

### ISSUE THREAD

**Issue by r0b-** [romanschejbal/gassetic#70]
Hi,

after updating to v1.0.7 gulp-replace is not working anymore.
My task definition looks like this
- { name: replace, args: ["../font", "fonts"], filter: ["icons.css"] }

Maybe the new version has problems with array args?

Thanks

**Comment by r0b-** [comment]
Still doesn't work for me with 1.0.9 :-(
Could you please another look?
(Another example task: `- { name: replace, args: ["url(\"/", "url(\"/some-prefix/"] }`)

Thanks!

**Comment by romanschejbal** [comment]
Right, there was a bug. Should be working now with latest 1.0.10. Let me know if not. Thanks!

**Comment by r0b-** [comment]
looks good - thanks!
